### PR TITLE
add mouseover and beforeunload to atom list

### PR DESCRIPTION
**Pull request by jxs**
[Review on Reviewable](https://reviewable.io/reviews/servo/string-cache/127)

### CODE REVIEW

**Comment by jdm** [comment]
Oh, we'll need to update the verions of heapsize used to the latest before this can merge.

**Comment by jdm** [comment]
Specifically heapsize_plugin to 0.1.2.

**Comment by jxs** [comment]
updated! :)

**Comment by jdm** [comment]
Oh, my mistake, we want 0.1.1. And I'll need to publish that.

**Comment by jdm** [comment]
Published.

**Comment by jxs** [comment]
no worries, updated :)

**Pull request merged**
