### PR TITLE
Add "before" and "after" atoms.

### PR DESCRIPTION
**Pull request by ecoal95**
Needed for https://github.com/servo/servo/pull/9567

[Review on Reviewable](https://reviewable.io/reviews/servo/string-cache/141)

### CODE REVIEW

**Comment by KiChjang** [comment]
Version bump!

**Comment by asajeffrey** [comment]
Looks good. Can you squash the two commits into one?

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/string-cache/141#-:-K9yl3-QiXtOH6-kDUwy:-1386810494)*

**Comment by KiChjang** [comment]
I disagree with squashing, because we wouldn't be able to tell which commit the version bump happened.

**Comment by asajeffrey** [comment]
Fine by me.

@bors-servo: r+

**Comment by ecoal95** [comment]
I'd wait to land this until the approach taken in https://github.com/servo/servo/pull/9567 is decided. There might be a chance this is not needed.

Re: squashing, I don't mind doing it. I think it's fine since it's a one-commit release.

**Comment by KiChjang** [comment]
`git commit --amend` followed by a `git push -f` should fix the status on homu.

**Comment by asajeffrey** [comment]
OK, though the cost for adding new static atoms is pretty small, and we're quite likely to want before and after at some point.

**Comment by ecoal95** [comment]
@asajeffrey: Merge it if you want then, I personally won't add unneeded atoms, but I agree these are likely to be desirable at some point :)

**Comment by asajeffrey** [comment]
We can leave it open for the moment, and wait for the dust to settle on https://github.com/servo/servo/pull/9567.

**Comment by ecoal95** [comment]
Closing this since https://github.com/servo/servo/pull/9567 implementation didn't finally need this.

**Pull request closed without merging**
