### PR TITLE
Add "referrerPolicy" to static_atom_list

### PR DESCRIPTION
**Pull request by TheKK**
for servo/servo#11861

---
This change is [Reviewable](https://reviewable.io/reviews/servo/string-cache/173)

### CODE REVIEW

**Comment by Manishearth** [comment]
I think you need both the lowercase and camelCase versions. Not sure though

**Comment by TheKK** [comment]
https://html.spec.whatwg.org/multipage/semantics.html#the-a-element

If DOM interface `referrerPolicy` must reflect content attribute `referrerpolicy`, does this mean we only need the lowercase one for storing Element's content attribute?

**Comment by Manishearth** [comment]
I think we only need the lowercase one

**Comment by TheKK** [comment]
Okay, fixed!

**Comment by jdm** [comment]
We'll need to bump the version number and publish, too.

**Pull request merged**
