### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hcpl**
This change is [Reviewable](https://reviewable.io/reviews/servo/string-cache/203)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Let’s coordinate this with other Servo dependencies: https://github.com/servo/servo/issues/20497

**Comment by SimonSapin** [comment]
`quote!` only works with a literal (statically-known) value. But maybe something like `format!("0x{:016x}").parse::<TokenStream>().unwrap()` would work?

**Comment by SimonSapin** [comment]
That said we don’t really need it, try this if you feel like it.

**Comment by hcpl** [comment]
> But maybe something like `format!("0x{:016x}").parse::<TokenStream>().unwrap()` would work?

Ah yeah, this is the right one.

And I've implemented it anyway so that numbers in `${OUT_DIR}/test_atom.rs` look better.

**Comment by SimonSapin** [comment]
Thanks!

@bors-servo r+

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/string-cache/203#-:-L9jtoA2541qT4Itcr-n:b-9kwh8u)*

**Pull request merged**
