### PR TITLE
Use the quote crate for code generation

### PR DESCRIPTION
**Pull request by SimonSapin**
r? @nox

---
This change is [Reviewable](https://reviewable.io/reviews/servo/string-cache/180)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Blocked on #181.

**Comment by SimonSapin** [comment]
This fails in the stable channel (but not beta or nigthly) because `quote! { $crate::some::path }` expands to a `Tokens` that contains `quote :: some :: path` instead of the expected `$ crate :: some :: path`. This looks like a bug in rustc that’s already solved, so let’s wait until the fix reaches the stable channel.

**Comment by nox** [comment]
Is this still relevant?

**Comment by SimonSapin** [comment]
It’s not very important since it doesn’t change anything for users of the library, but I think it makes the code nicer.

I’ve restarted https://travis-ci.org/servo/string-cache/builds/179028002 which is now green, it looks like the bug fix has reached the stable channel.

**Pull request merged**
